Repository depromeet/17th-team5-Android, pull requests merged in 2025-09, with the labels that each got.

#2 [Chore] Update README.md
  README.md
Labels: Chore

#3 [Chore] PR 템플릿 생성
  .github/pull_request_template.md
Labels: Chore

#4 [Chore] hilt custom plugin 생성
  app/build.gradle.kts
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/AndroidHiltConventionPlugin.kt
  gradle/libs.versions.toml
Labels: Chore

#6 [Chore] data 모듈 생성
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/depromeet/team5/DepromeetApplication.kt
  app/src/main/java/com/depromeet/team5/MainActivity.kt
  core/data/build.gradle.kts
  core/data/src/main/java/com/depromeet/team5/core/data/di/RepositoryModule.kt
  core/data/src/main/java/com/depromeet/team5/core/data/repositoryimpl/TestRepositoryImpl.kt
  core/domain/src/main/java/com/depromeet/team5/core/domain/repository/TestRepository.kt
  core/domain/src/main/java/com/depromeet/team5/core/domain/usecase/TestUseCase.kt
  settings.gradle.kts
Labels: Feature

#7 [Chore] localdatasource 모듈 생성
  app/build.gradle.kts
  build-logic/convention/src/main/kotlin/AndroidLibraryConventionPlugin.kt
  build.gradle.kts
  core/data/src/main/java/com/depromeet/team5/core/data/datasource/LocalDataSource.kt
  core/data/src/main/java/com/depromeet/team5/core/data/model/TestData.kt
  core/data/src/main/java/com/depromeet/team5/core/data/repositoryimpl/TestRepositoryImpl.kt
  core/localdatasource/build.gradle.kts
  core/localdatasource/src/androidTest/java/com/depromeet/team5/core/ExampleInstrumentedTest.kt
  core/localdatasource/src/main/java/com/depromeet/team5/core/LocalDataSourceImpl.kt
  core/localdatasource/src/main/java/com/depromeet/team5/core/di/LocalDataSourceModule.kt
  core/localdatasource/src/main/java/com/depromeet/team5/core/mapper/DataMapper.kt
  core/localdatasource/src/main/java/com/depromeet/team5/core/mapper/Mapper.kt
  core/localdatasource/src/main/java/com/depromeet/team5/core/model/TestLocalData.kt
  core/localdatasource/src/test/java/com/depromeet/team5/core/ExampleUnitTest.kt
  settings.gradle.kts
Labels: Feature

#8 [Chore] remotedatasource 모듈 생성
  app/build.gradle.kts
  core/data/src/main/java/com/depromeet/team5/core/data/datasource/RemoteDataSource.kt
  core/data/src/main/java/com/depromeet/team5/core/data/repositoryimpl/TestRepositoryImpl.kt
  core/localdatasource/build.gradle.kts
  core/remotedatasource/build.gradle.kts
  core/remotedatasource/src/androidTest/java/com/depromeet/team5/core/remotedatasource/ExampleInstrumentedTest.kt
  core/remotedatasource/src/main/java/com/depromeet/team5/core/remotedatasource/RemoteDataSourceImpl.kt
  core/remotedatasource/src/main/java/com/depromeet/team5/core/remotedatasource/di/RemoteDataSourceModule.kt
  core/remotedatasource/src/main/java/com/depromeet/team5/core/remotedatasource/mapper/DataMapper.kt
  core/remotedatasource/src/main/java/com/depromeet/team5/core/remotedatasource/mapper/Mapper.kt
  core/remotedatasource/src/main/java/com/depromeet/team5/core/remotedatasource/model/TestRemoteResponse.kt
  core/remotedatasource/src/test/java/com/depromeet/team5/core/remotedatasource/ExampleUnitTest.kt
  settings.gradle.kts
Labels: Feature

#9 [Chore] NM5-2 retrofit 모듈 생성
  app/build.gradle.kts
  core/remotedatasource/src/main/java/com/depromeet/team5/core/remotedatasource/RemoteDataSourceImpl.kt
  core/remotedatasource/src/main/java/com/depromeet/team5/core/remotedatasource/apisource/TestApiSource.kt
  core/retrofit/build.gradle.kts
  core/retrofit/src/androidTest/java/com/depromeet/team5/core/retrofit/ExampleInstrumentedTest.kt
  core/retrofit/src/main/AndroidManifest.xml
  core/retrofit/src/main/java/com/depromeet/team5/core/retrofit/Constant.kt
  core/retrofit/src/main/java/com/depromeet/team5/core/retrofit/api/TestApi.kt
  core/retrofit/src/main/java/com/depromeet/team5/core/retrofit/apisourceimpl/TestApiSourceImpl.kt
  core/retrofit/src/main/java/com/depromeet/team5/core/retrofit/di/ApiModule.kt
  core/retrofit/src/main/java/com/depromeet/team5/core/retrofit/di/ApiSourceModule.kt
  core/retrofit/src/main/java/com/depromeet/team5/core/retrofit/di/ConverterModule.kt
  core/retrofit/src/main/java/com/depromeet/team5/core/retrofit/di/InterceptorModule.kt
  core/retrofit/src/main/java/com/depromeet/team5/core/retrofit/di/OkHttpClientModule.kt
  core/retrofit/src/main/java/com/depromeet/team5/core/retrofit/di/RetrofitModule.kt
  core/retrofit/src/main/java/com/depromeet/team5/core/retrofit/mapper/Mapper.kt
  core/retrofit/src/main/java/com/depromeet/team5/core/retrofit/mapper/ResponseMapper.kt
  core/retrofit/src/main/java/com/depromeet/team5/core/retrofit/model/TestApiResponse.kt
  core/retrofit/src/test/java/com/depromeet/team5/core/retrofit/ExampleUnitTest.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: Chore

#10 [Chore] navigation 모듈 및 features 모듈 생성
  settings.gradle.kts
Labels: Chore

#13 [Feature] NM5-3 검색 뷰 UI 구현
  app/build.gradle.kts
  features/search/build.gradle.kts
  features/search/src/androidTest/java/com/depromeet/team5/features/search/ExampleInstrumentedTest.kt
  features/search/src/main/java/com/depromeet/team5/features/search/SearchScreen.kt
  features/search/src/main/java/com/depromeet/team5/features/search/SearchViewModel.kt
  features/search/src/main/java/com/depromeet/team5/features/search/UiState.kt
  features/search/src/main/java/com/depromeet/team5/features/search/component/SearchListItem.kt
  features/search/src/main/java/com/depromeet/team5/features/search/component/SearchTextField.kt
  features/search/src/main/java/com/depromeet/team5/features/search/model/StockData.kt
  features/search/src/main/res/values/strings.xml
  features/search/src/test/java/com/depromeet/team5/features/search/ExampleUnitTest.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: Feature

#17 [Feature] NM5-11 디자인 시스템 컴포넌트 (version1 마무리)
  core/designsystem/src/main/java/com/depromeet/team5/core/designsystem/component/HedgeButton.kt
  core/designsystem/src/main/java/com/depromeet/team5/core/designsystem/component/HedgeSegment.kt
  core/designsystem/src/main/java/com/depromeet/team5/core/designsystem/component/HedgeSwitch.kt
  core/designsystem/src/main/java/com/depromeet/team5/core/designsystem/component/HedgeTextField.kt
  core/designsystem/src/main/java/com/depromeet/team5/core/designsystem/component/HedgeToast.kt
  core/designsystem/src/main/java/com/depromeet/team5/core/designsystem/component/HedgeTopBar.kt
  core/designsystem/src/main/java/com/depromeet/team5/core/designsystem/foundation/HedgeColor.kt
  core/designsystem/src/main/res/drawable/ic_toast_check.xml
  core/designsystem/src/main/res/drawable/ic_toast_copy.xml
  core/designsystem/src/main/res/drawable/ic_toast_error.xml
Labels: Feature

#19 [Feature] NM5-14 브랜드 색상 적용
  core/designsystem/src/main/java/com/depromeet/team5/core/designsystem/component/HedgeButton.kt
  core/designsystem/src/main/java/com/depromeet/team5/core/designsystem/component/HedgeTextField.kt
  core/designsystem/src/main/java/com/depromeet/team5/core/designsystem/component/HedgeToast.kt
  core/designsystem/src/main/java/com/depromeet/team5/core/designsystem/foundation/HedgeColor.kt
Labels: Feature

#16 [Feature] NM5-10 app 모듈 네비게이션 구현
  app/src/main/java/com/depromeet/team5/HedgeNavHost.kt
  app/src/main/java/com/depromeet/team5/MainActivity.kt
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/AndroidLibraryConventionPlugin.kt
  build-logic/convention/src/main/kotlin/com/depromeet/team5/AndroidCompose.kt
  build.gradle.kts
  features/search/src/main/java/com/depromeet/team5/features/search/SearchNavigation.kt
  features/search/src/main/java/com/depromeet/team5/features/search/SearchScreen.kt
  features/search/src/main/java/com/depromeet/team5/features/search/component/SearchTextField.kt
  gradle/libs.versions.toml
Labels: Feature

#18 [Feature] 회고하기 화면 구현
  app/build.gradle.kts
  features/retrospect/build.gradle.kts
  features/retrospect/src/androidTest/java/com/depromeet/team5/core/features/retrospect/ExampleInstrumentedTest.kt
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/annotation/SavedStateHandleKeyType.kt
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/extensions/CollectExtensions.kt
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/extensions/HedgeStateLazy.kt
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/screen/RetrospectScreen.kt
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/screen/RetrospectViewModel.kt
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/screen/component/HedgeDatePickerDialog.kt
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/screen/component/HedgeSwitch.kt
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/screen/component/HedgeTextField.kt
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/screen/component/HedgeToolbar.kt
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/screen/visualtransmation/DateVisualTransformation.kt
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/screen/visualtransmation/KoreanCurrencyVisualTransformation.kt
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/screen/visualtransmation/USDCurrencyVisualTransformation.kt
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/screen/visualtransmation/UnitTransformation.kt
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/state/TextFieldState.kt
  features/retrospect/src/main/res/drawable/icon_arrow_left.xml
  features/retrospect/src/main/res/values/colors.xml
  features/retrospect/src/main/res/values/strings.xml
  features/retrospect/src/test/java/com/depromeet/team5/core/features/retrospect/ExampleUnitTest.kt
  settings.gradle.kts
Labels: Feature

#23 [Feature] NM5-18 홈 화면 구현
  app/build.gradle.kts
  app/src/main/java/com/depromeet/team5/HedgeNavHost.kt
  features/home/build.gradle.kts
  features/home/src/androidTest/java/com/depromeet/team5/features/home/ExampleInstrumentedTest.kt
  features/home/src/main/java/com/depromeet/team5/features/home/HomeNavigation.kt
  features/home/src/main/java/com/depromeet/team5/features/home/HomeScreen.kt
  features/home/src/main/java/com/depromeet/team5/features/home/component/HomeFloatingActionButton.kt
  features/home/src/main/res/drawable/ic_close.xml
  features/home/src/main/res/drawable/ic_pencil.xml
  features/home/src/main/res/drawable/ic_plus.xml
  features/home/src/main/res/values/strings.xml
  features/home/src/test/java/com/depromeet/team5/features/home/ExampleUnitTest.kt
  features/search/src/main/java/com/depromeet/team5/features/search/SearchNavigation.kt
  settings.gradle.kts
Labels: Feature

#28 [Feature]NM5-15 투자 원칙 화면 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  core/designsystem/src/main/java/com/depromeet/team5/core/designsystem/foundation/HedgeIcon.kt
  core/designsystem/src/main/java/com/depromeet/team5/core/designsystem/foundation/HedgeTypography.kt
  core/designsystem/src/main/res/drawable/ic_edit.xml
  core/designsystem/src/main/res/drawable/ic_pencil.xml
  core/designsystem/src/main/res/drawable/ic_trash.xml
  features/reasons/build.gradle.kts
  features/reasons/src/androidTest/java/com/depromeet/team5/feature/reasons/ExampleInstrumentedTest.kt
  features/reasons/src/main/java/com/depromeet/team5/feature/reasons/ReasonNavigation.kt
  features/reasons/src/main/java/com/depromeet/team5/feature/reasons/ReasonScreen.kt
  features/reasons/src/main/java/com/depromeet/team5/feature/reasons/ReasonViewModel.kt
  features/reasons/src/main/java/com/depromeet/team5/feature/reasons/ui/AnalysisPip.kt
  features/reasons/src/main/java/com/depromeet/team5/feature/reasons/ui/AutoScrollTextField.kt
  features/reasons/src/main/java/com/depromeet/team5/feature/reasons/ui/EmotionBottomSheet.kt
  features/reasons/src/main/java/com/depromeet/team5/feature/reasons/ui/EmotionSlider.kt
  features/reasons/src/main/java/com/depromeet/team5/feature/reasons/ui/PrincipleBottomSheet.kt
  features/reasons/src/main/res/drawable-hdpi/buy.png
  features/reasons/src/main/res/drawable-hdpi/sell.png
  features/reasons/src/main/res/drawable-mdpi/buy.png
  features/reasons/src/main/res/drawable-mdpi/sell.png
  features/reasons/src/main/res/drawable-xhdpi/buy.png
  features/reasons/src/main/res/drawable-xhdpi/sell.png
  features/reasons/src/main/res/drawable-xxhdpi/buy.png
  features/reasons/src/main/res/drawable-xxhdpi/sell.png
  features/reasons/src/main/res/drawable-xxxhdpi/buy.png
  features/reasons/src/main/res/drawable-xxxhdpi/sell.png
  features/reasons/src/main/res/drawable/ic_add_emotion.xml
  features/reasons/src/main/res/drawable/ic_book.xml
  features/reasons/src/main/res/drawable/ic_check.xml
  features/reasons/src/main/res/drawable/ic_checklist.xml
  features/reasons/src/main/res/drawable/ic_close.xml
  features/reasons/src/main/res/drawable/ic_close_small.xml
  features/reasons/src/main/res/drawable/ic_company_logo.xml
  features/reasons/src/main/res/drawable/ic_emotion_anxious.xml
  features/reasons/src/main/res/drawable/ic_emotion_anxious_off.xml
  features/reasons/src/main/res/drawable/ic_emotion_anxious_on.xml
  features/reasons/src/main/res/drawable/ic_emotion_confidence.xml
  features/reasons/src/main/res/drawable/ic_emotion_confidence_off.xml
  features/reasons/src/main/res/drawable/ic_emotion_confidence_on.xml
  features/reasons/src/main/res/drawable/ic_emotion_conviction.xml
  features/reasons/src/main/res/drawable/ic_emotion_conviction_off.xml
  features/reasons/src/main/res/drawable/ic_emotion_conviction_on.xml
  features/reasons/src/main/res/drawable/ic_emotion_impulse.xml
  features/reasons/src/main/res/drawable/ic_emotion_impulse_off.xml
  features/reasons/src/main/res/drawable/ic_emotion_impulse_on.xml
  features/reasons/src/main/res/drawable/ic_emotion_neutral.xml
  features/reasons/src/main/res/drawable/ic_emotion_neutral_off.xml
  features/reasons/src/main/res/drawable/ic_emotion_neutral_on.xml
  features/reasons/src/main/res/drawable/ic_principle_logo.xml
  features/reasons/src/main/res/drawable/ic_thumb.xml
  features/reasons/src/main/res/drawable/ic_twinkle.xml
  features/reasons/src/main/res/values/strings.xml
  features/reasons/src/test/java/com/depromeet/team5/feature/reasons/ExampleUnitTest.kt
  settings.gradle.kts
Labels: Feature

#30 [Feature] NM5-23 검색 매도입력 네비게이션 구현
  app/src/main/java/com/depromeet/team5/HedgeNavHost.kt
  core/model/src/main/java/com/depromeet/team5/core/model/request/CreateRetrospectionParams.kt
  features/retrospect/build.gradle.kts
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/screen/RetrospectNavigation.kt
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/screen/RetrospectScreen.kt
  features/search/build.gradle.kts
  features/search/src/main/java/com/depromeet/team5/features/search/SearchNavigation.kt
Labels: Feature

#37 [Refactor] 회고하기 화면 빠진 부분 추가
  app/src/main/java/com/depromeet/team5/HedgeNavHost.kt
  features/retrospect/build.gradle.kts
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/extensions/HedgeStateLazy.kt
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/screen/RetrospectNavigation.kt
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/screen/RetrospectScreen.kt
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/screen/RetrospectViewModel.kt
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/screen/component/HedgeTextField.kt
  features/retrospect/src/main/res/values/strings.xml
Labels: Refactor

#42 [Chore] currency 추가
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/screen/RetrospectScreen.kt
Labels: Chore

#45 [Feature] 피드백 엔드포인트 추가
  core/domain/src/main/java/com/depromeet/team5/core/domain/usecase/CreateRetrospectionUseCase.kt
  core/model/src/main/java/com/depromeet/team5/core/model/mapper/Mapper.kt
  core/retrofit/src/main/java/com/depromeet/team5/core/retrofit/apisourceimpl/HedgeApiSourceImpl.kt
  core/retrofit/src/main/java/com/depromeet/team5/core/retrofit/model/RetrospectionResponse.kt
  features/feedback/src/main/java/com/depromeet/team5/features/feedback/screen/AiFeedbackViewModel.kt
  features/feedback/src/main/java/com/depromeet/team5/features/feedback/screen/FeedbackScreen.kt
Labels: Feature

#46 [Fix] 뒤로가기 버튼 액션 추가
  features/retrospect/src/main/java/com/depromeet/team5/features/retrospect/screen/RetrospectScreen.kt
Labels: Fix
